
## @Author Yongqian Huang, created at 07/2020
- name: Deploy Application
  hosts: webservers
  vars:
    server_dir: "/var/www/nly"
    user: "root"
    systemd_dir: "/etc/systemd/system"
  tasks:    
    - name: Upload server
      become: yes
      copy:
        src: "../artifacts/server.tgz"
        dest: "{{server_dir}}"
    
    - name: Extract server
      become: yes
      unarchive: 
        src: "{{server_dir}}/server.tgz"
        dest: "{{server_dir}}"
        copy: no
    
    - name: Copy server files
      become: yes
      shell: "cp -a {{server_dir}}/package/. {{server_dir}}"
    
    - name: Install packages
      become: yes
      npm:
        path: "{{server_dir}}"
    
    - name: Delete old pm2 process
      command: pm2 delete nly
      ignore_errors: yes

    - name: Start pm2
      shell: "cd {{server_dir}} && yarn prod"